// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum RecordOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A complete log record with field permission rings (Ring 0–3).
///
/// Ring semantics (from design doc §14.4):
///   Ring 0 — Kernel-core    (ID, timestamp, signature, origin LSN)
///   Ring 1 — System trusted (level, message, host info, tracing, exception)
///   Ring 2 — Verified plugin fields (not yet represented in schema — future)
///   Ring 3 — Legacy untrusted extension blob (migration compatibility only)
///
/// All fields are optional (FlatBuffers `table` semantics) so the schema can
/// evolve without breaking existing consumers.  Missing fields default to
/// zero / empty as documented per field.
pub struct Record<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Record<'a> {
  type Inner = Record<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Record<'a> {
  pub const VT_ID_HI: ::flatbuffers::VOffsetT = 4;
  pub const VT_ID_LO: ::flatbuffers::VOffsetT = 6;
  pub const VT_TIMESTAMP_HI: ::flatbuffers::VOffsetT = 8;
  pub const VT_TIMESTAMP_LO: ::flatbuffers::VOffsetT = 10;
  pub const VT_SIGNATURE: ::flatbuffers::VOffsetT = 12;
  pub const VT_ORIGIN_LSN: ::flatbuffers::VOffsetT = 14;
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 16;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 18;
  pub const VT_SOURCE_FILE: ::flatbuffers::VOffsetT = 20;
  pub const VT_SOURCE_FUNCTION: ::flatbuffers::VOffsetT = 22;
  pub const VT_SOURCE_LINE: ::flatbuffers::VOffsetT = 24;
  pub const VT_SOURCE_COLUMN: ::flatbuffers::VOffsetT = 26;
  pub const VT_THREAD_ID: ::flatbuffers::VOffsetT = 28;
  pub const VT_THREAD_NAME: ::flatbuffers::VOffsetT = 30;
  pub const VT_PROCESS_ID: ::flatbuffers::VOffsetT = 32;
  pub const VT_PROCESS_NAME: ::flatbuffers::VOffsetT = 34;
  pub const VT_HOST_NAME: ::flatbuffers::VOffsetT = 36;
  pub const VT_CONTAINER_ID: ::flatbuffers::VOffsetT = 38;
  pub const VT_APP_NAME: ::flatbuffers::VOffsetT = 40;
  pub const VT_APP_VERSION: ::flatbuffers::VOffsetT = 42;
  pub const VT_ENVIRONMENT: ::flatbuffers::VOffsetT = 44;
  pub const VT_USER_ID: ::flatbuffers::VOffsetT = 46;
  pub const VT_SESSION_ID: ::flatbuffers::VOffsetT = 48;
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 50;
  pub const VT_TRACE_ID: ::flatbuffers::VOffsetT = 52;
  pub const VT_SPAN_ID: ::flatbuffers::VOffsetT = 54;
  pub const VT_COROUTINE_ID: ::flatbuffers::VOffsetT = 56;
  pub const VT_EXCEPTION_TYPE: ::flatbuffers::VOffsetT = 58;
  pub const VT_EXCEPTION_MESSAGE: ::flatbuffers::VOffsetT = 60;
  pub const VT_EXCEPTION_STACKTRACE: ::flatbuffers::VOffsetT = 62;
  pub const VT_EXCEPTION_CODE: ::flatbuffers::VOffsetT = 64;
  pub const VT_LABELS: ::flatbuffers::VOffsetT = 66;
  pub const VT_LSN: ::flatbuffers::VOffsetT = 68;
  pub const VT_PREV_HASH: ::flatbuffers::VOffsetT = 70;
  pub const VT_SECURITY_GAP: ::flatbuffers::VOffsetT = 72;
  pub const VT_AUDIT_TAGS: ::flatbuffers::VOffsetT = 74;
  pub const VT_EXT_DATA: ::flatbuffers::VOffsetT = 76;
  pub const VT_EXT_CRC32C: ::flatbuffers::VOffsetT = 78;
  pub const VT_POOL_INDEX: ::flatbuffers::VOffsetT = 80;
  pub const VT_FLAGS: ::flatbuffers::VOffsetT = 82;
  pub const VT_CONTENT_HASH: ::flatbuffers::VOffsetT = 84;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Record { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Record<'bldr>> {
    let mut builder = RecordBuilder::new(_fbb);
    builder.add_lsn(args.lsn);
    builder.add_coroutine_id(args.coroutine_id);
    builder.add_thread_id(args.thread_id);
    builder.add_origin_lsn(args.origin_lsn);
    builder.add_timestamp_lo(args.timestamp_lo);
    builder.add_timestamp_hi(args.timestamp_hi);
    builder.add_id_lo(args.id_lo);
    builder.add_id_hi(args.id_hi);
    builder.add_flags(args.flags);
    builder.add_pool_index(args.pool_index);
    builder.add_ext_crc32c(args.ext_crc32c);
    if let Some(x) = args.content_hash { builder.add_content_hash(x); }
    if let Some(x) = args.ext_data { builder.add_ext_data(x); }
    if let Some(x) = args.audit_tags { builder.add_audit_tags(x); }
    if let Some(x) = args.prev_hash { builder.add_prev_hash(x); }
    if let Some(x) = args.labels { builder.add_labels(x); }
    builder.add_exception_code(args.exception_code);
    if let Some(x) = args.exception_stacktrace { builder.add_exception_stacktrace(x); }
    if let Some(x) = args.exception_message { builder.add_exception_message(x); }
    if let Some(x) = args.exception_type { builder.add_exception_type(x); }
    if let Some(x) = args.span_id { builder.add_span_id(x); }
    if let Some(x) = args.trace_id { builder.add_trace_id(x); }
    if let Some(x) = args.request_id { builder.add_request_id(x); }
    if let Some(x) = args.session_id { builder.add_session_id(x); }
    if let Some(x) = args.user_id { builder.add_user_id(x); }
    if let Some(x) = args.environment { builder.add_environment(x); }
    if let Some(x) = args.app_version { builder.add_app_version(x); }
    if let Some(x) = args.app_name { builder.add_app_name(x); }
    if let Some(x) = args.container_id { builder.add_container_id(x); }
    if let Some(x) = args.host_name { builder.add_host_name(x); }
    if let Some(x) = args.process_name { builder.add_process_name(x); }
    builder.add_process_id(args.process_id);
    if let Some(x) = args.thread_name { builder.add_thread_name(x); }
    builder.add_source_column(args.source_column);
    builder.add_source_line(args.source_line);
    if let Some(x) = args.source_function { builder.add_source_function(x); }
    if let Some(x) = args.source_file { builder.add_source_file(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.signature { builder.add_signature(x); }
    builder.add_security_gap(args.security_gap);
    builder.add_level(args.level);
    builder.finish()
  }


  /// Globally unique record ID (modified snowflake algorithm).
  /// Stored as two uint64 halves because FlatBuffers lacks native u128.
  /// id_hi: milliseconds since custom epoch (high 64 bits)
  #[inline]
  pub fn id_hi(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_ID_HI, Some(0)).unwrap()}
  }
  /// Low 64 bits of the 128-bit record ID.
  /// id_lo: sequence number + worker-id + datacentre-id (low 64 bits)
  #[inline]
  pub fn id_lo(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_ID_LO, Some(0)).unwrap()}
  }
  /// Nanosecond-precision UTC timestamp.
  /// Stored as two uint64 halves (seconds since UNIX epoch, nanoseconds).
  /// timestamp_hi: whole seconds since UNIX epoch
  #[inline]
  pub fn timestamp_hi(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_TIMESTAMP_HI, Some(0)).unwrap()}
  }
  /// Fractional nanoseconds component of the timestamp.
  /// timestamp_lo: nanoseconds (0..999_999_999)
  #[inline]
  pub fn timestamp_lo(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_TIMESTAMP_LO, Some(0)).unwrap()}
  }
  /// Ed25519 signature covering Ring 0 + Ring 1 fields.
  /// 64 bytes; absent until the record is signed by the core engine.
  #[inline]
  pub fn signature(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Record::VT_SIGNATURE, None).unwrap()}
  }
  /// Origin LSN (Log Sequence Number) if this record was forwarded from
  /// another DoLogger node in a multi-node deployment.  0 = local record.
  #[inline]
  pub fn origin_lsn(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_ORIGIN_LSN, Some(0)).unwrap()}
  }
  /// Log level (see LogLevel enum in record/mod.rs):
  ///   0 = Trace, 1 = Debug, 2 = Info, 3 = Warn,
  ///   4 = Error, 5 = Fatal, 6 = Audit
  #[inline]
  pub fn level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Record::VT_LEVEL, Some(2)).unwrap()}
  }
  /// Log message body (UTF-8).  May be truncated by the RecordString
  /// inline buffer to 255 bytes in the in-memory representation;
  /// SIF preserves the full message when available.
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_MESSAGE, None)}
  }
  /// Source file path (e.g. "src/main.rs") — optional.
  #[inline]
  pub fn source_file(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_SOURCE_FILE, None)}
  }
  /// Source function name — optional.
  #[inline]
  pub fn source_function(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_SOURCE_FUNCTION, None)}
  }
  /// Source line number (1-based).
  #[inline]
  pub fn source_line(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_SOURCE_LINE, Some(0)).unwrap()}
  }
  /// Source column number (1-based).
  #[inline]
  pub fn source_column(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_SOURCE_COLUMN, Some(0)).unwrap()}
  }
  /// OS thread ID (platform-specific; on Linux this is the tid).
  #[inline]
  pub fn thread_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_THREAD_ID, Some(0)).unwrap()}
  }
  /// Human-readable thread name (may be set via pthread_setname_np or similar).
  #[inline]
  pub fn thread_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_THREAD_NAME, None)}
  }
  /// OS process ID.
  #[inline]
  pub fn process_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_PROCESS_ID, Some(0)).unwrap()}
  }
  /// Process name (argv[0] or /proc/self/comm equivalent).
  #[inline]
  pub fn process_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_PROCESS_NAME, None)}
  }
  /// Host name (FQDN when available).
  #[inline]
  pub fn host_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_HOST_NAME, None)}
  }
  /// Container ID (Docker / Kubernetes container ID, when running containerised).
  #[inline]
  pub fn container_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_CONTAINER_ID, None)}
  }
  /// Application name (e.g. "my-service").
  #[inline]
  pub fn app_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_APP_NAME, None)}
  }
  /// Application version (SemVer string, e.g. "1.2.3").
  #[inline]
  pub fn app_version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_APP_VERSION, None)}
  }
  /// Deployment environment: "dev", "test", "staging", "prod".
  #[inline]
  pub fn environment(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_ENVIRONMENT, None)}
  }
  /// Authenticated user identifier (e.g. UUID or email).
  #[inline]
  pub fn user_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_USER_ID, None)}
  }
  /// Session identifier for correlating records within a single user session.
  #[inline]
  pub fn session_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_SESSION_ID, None)}
  }
  /// Request identifier (W3C Trace Context / OpenTelemetry compatible).
  #[inline]
  pub fn request_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_REQUEST_ID, None)}
  }
  /// Distributed trace ID (W3C Trace Context / OpenTelemetry compatible).
  #[inline]
  pub fn trace_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_TRACE_ID, None)}
  }
  /// Span ID within a distributed trace.
  #[inline]
  pub fn span_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_SPAN_ID, None)}
  }
  /// Coroutine / async-task identifier (tokio::task::Id, goroutine id, etc.).
  #[inline]
  pub fn coroutine_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_COROUTINE_ID, Some(0)).unwrap()}
  }
  /// Exception type name (e.g. "std::runtime_error", "panic", "anyhow::Error").
  #[inline]
  pub fn exception_type(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_EXCEPTION_TYPE, None)}
  }
  /// Exception detail message.
  #[inline]
  pub fn exception_message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_EXCEPTION_MESSAGE, None)}
  }
  /// Exception stack trace (multi-line string).
  #[inline]
  pub fn exception_stacktrace(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_EXCEPTION_STACKTRACE, None)}
  }
  /// Platform-specific error code (errno, HRESULT, exit code).
  #[inline]
  pub fn exception_code(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Record::VT_EXCEPTION_CODE, Some(0)).unwrap()}
  }
  /// JSON object string of key-value labels attached to this record.
  /// Example: {"request_size": 1024, "endpoint": "/api/v1/users"}
  #[inline]
  pub fn labels(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_LABELS, None)}
  }
  /// Log Sequence Number — monotonically increasing counter.
  /// Required for audit trail integrity verification.
  #[inline]
  pub fn lsn(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Record::VT_LSN, Some(0)).unwrap()}
  }
  /// SHA-256 hash of the previous audit record's (LSN || Signature).
  /// 32 bytes; forms a cryptographically-linked chain for audit records.
  #[inline]
  pub fn prev_hash(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Record::VT_PREV_HASH, None).unwrap()}
  }
  /// WORM LSN gap marker.  true when a gap in the LSN sequence has been
  /// detected (e.g. due to ring buffer overflow), breaking the audit chain.
  #[inline]
  pub fn security_gap(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Record::VT_SECURITY_GAP, Some(false)).unwrap()}
  }
  /// JSON-encoded array tracking all Ring 2 field modifications.
  /// Each entry records plugin_id, version, field name, value, and timestamp.
  /// Example: [{"plugin":"enricher","ver":"1.0","field":"verified.user_role","val":"admin","ts":1718123456789}]
  #[inline]
  pub fn audit_tags(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_AUDIT_TAGS, None)}
  }
  /// Legacy extension blob retained for compatibility decoding only.
  /// Current records store ext.* fields as KV entries covered by content_hash.
  #[inline]
  pub fn ext_data(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Record::VT_EXT_DATA, None)}
  }
  /// Legacy CRC32C checksum associated with ext_data compatibility frames.
  #[inline]
  pub fn ext_crc32c(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_EXT_CRC32C, Some(0)).unwrap()}
  }
  /// Slot index in the object pool.  Used by the pool to return the record
  /// after the sink has consumed it.  Zero when not pooled.
  #[inline]
  pub fn pool_index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_POOL_INDEX, Some(0)).unwrap()}
  }
  /// Record flags bitfield:
  ///   0x01 — in_use (slot is allocated)
  ///   0x02 — signed (Ed25519 signature populated)
  ///   0x04 — audit  (record level is Audit; WORM chain applies)
  #[inline]
  pub fn flags(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Record::VT_FLAGS, Some(0)).unwrap()}
  }
  /// SHA-256 canonical-serialization hash (A.3) of the record content.
  /// 32 bytes; nonzero for AUDIT records (part of the tamper-evident chain).
  /// Absent on records written before this field existed (schema evolution).
  #[inline]
  pub fn content_hash(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Record::VT_CONTENT_HASH, None)}
  }
}

impl ::flatbuffers::Verifiable for Record<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id_hi", Self::VT_ID_HI, false)?
     .visit_field::<u64>("id_lo", Self::VT_ID_LO, false)?
     .visit_field::<u64>("timestamp_hi", Self::VT_TIMESTAMP_HI, false)?
     .visit_field::<u64>("timestamp_lo", Self::VT_TIMESTAMP_LO, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("signature", Self::VT_SIGNATURE, true)?
     .visit_field::<u64>("origin_lsn", Self::VT_ORIGIN_LSN, false)?
     .visit_field::<u8>("level", Self::VT_LEVEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_file", Self::VT_SOURCE_FILE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_function", Self::VT_SOURCE_FUNCTION, false)?
     .visit_field::<u32>("source_line", Self::VT_SOURCE_LINE, false)?
     .visit_field::<u32>("source_column", Self::VT_SOURCE_COLUMN, false)?
     .visit_field::<u64>("thread_id", Self::VT_THREAD_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("thread_name", Self::VT_THREAD_NAME, false)?
     .visit_field::<u32>("process_id", Self::VT_PROCESS_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("process_name", Self::VT_PROCESS_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("host_name", Self::VT_HOST_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("container_id", Self::VT_CONTAINER_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("app_name", Self::VT_APP_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("app_version", Self::VT_APP_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("environment", Self::VT_ENVIRONMENT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("user_id", Self::VT_USER_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("session_id", Self::VT_SESSION_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("trace_id", Self::VT_TRACE_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("span_id", Self::VT_SPAN_ID, false)?
     .visit_field::<u64>("coroutine_id", Self::VT_COROUTINE_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("exception_type", Self::VT_EXCEPTION_TYPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("exception_message", Self::VT_EXCEPTION_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("exception_stacktrace", Self::VT_EXCEPTION_STACKTRACE, false)?
     .visit_field::<i32>("exception_code", Self::VT_EXCEPTION_CODE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("labels", Self::VT_LABELS, false)?
     .visit_field::<u64>("lsn", Self::VT_LSN, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("prev_hash", Self::VT_PREV_HASH, true)?
     .visit_field::<bool>("security_gap", Self::VT_SECURITY_GAP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("audit_tags", Self::VT_AUDIT_TAGS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ext_data", Self::VT_EXT_DATA, false)?
     .visit_field::<u32>("ext_crc32c", Self::VT_EXT_CRC32C, false)?
     .visit_field::<u32>("pool_index", Self::VT_POOL_INDEX, false)?
     .visit_field::<u32>("flags", Self::VT_FLAGS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("content_hash", Self::VT_CONTENT_HASH, false)?
     .finish();
    Ok(())
  }
}
pub struct RecordArgs<'a> {
    pub id_hi: u64,
    pub id_lo: u64,
    pub timestamp_hi: u64,
    pub timestamp_lo: u64,
    pub signature: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub origin_lsn: u64,
    pub level: u8,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub source_file: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub source_function: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub source_line: u32,
    pub source_column: u32,
    pub thread_id: u64,
    pub thread_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub process_id: u32,
    pub process_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub host_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub container_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub app_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub app_version: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub environment: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub user_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub session_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub request_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub trace_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub span_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub coroutine_id: u64,
    pub exception_type: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub exception_message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub exception_stacktrace: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub exception_code: i32,
    pub labels: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub lsn: u64,
    pub prev_hash: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub security_gap: bool,
    pub audit_tags: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ext_data: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ext_crc32c: u32,
    pub pool_index: u32,
    pub flags: u32,
    pub content_hash: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for RecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    RecordArgs {
      id_hi: 0,
      id_lo: 0,
      timestamp_hi: 0,
      timestamp_lo: 0,
      signature: None, // required field
      origin_lsn: 0,
      level: 2,
      message: None,
      source_file: None,
      source_function: None,
      source_line: 0,
      source_column: 0,
      thread_id: 0,
      thread_name: None,
      process_id: 0,
      process_name: None,
      host_name: None,
      container_id: None,
      app_name: None,
      app_version: None,
      environment: None,
      user_id: None,
      session_id: None,
      request_id: None,
      trace_id: None,
      span_id: None,
      coroutine_id: 0,
      exception_type: None,
      exception_message: None,
      exception_stacktrace: None,
      exception_code: 0,
      labels: None,
      lsn: 0,
      prev_hash: None, // required field
      security_gap: false,
      audit_tags: None,
      ext_data: None,
      ext_crc32c: 0,
      pool_index: 0,
      flags: 0,
      content_hash: None,
    }
  }
}

pub struct RecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id_hi(&mut self, id_hi: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_ID_HI, id_hi, 0);
  }
  #[inline]
  pub fn add_id_lo(&mut self, id_lo: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_ID_LO, id_lo, 0);
  }
  #[inline]
  pub fn add_timestamp_hi(&mut self, timestamp_hi: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_TIMESTAMP_HI, timestamp_hi, 0);
  }
  #[inline]
  pub fn add_timestamp_lo(&mut self, timestamp_lo: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_TIMESTAMP_LO, timestamp_lo, 0);
  }
  #[inline]
  pub fn add_signature(&mut self, signature: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_SIGNATURE, signature);
  }
  #[inline]
  pub fn add_origin_lsn(&mut self, origin_lsn: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_ORIGIN_LSN, origin_lsn, 0);
  }
  #[inline]
  pub fn add_level(&mut self, level: u8) {
    self.fbb_.push_slot::<u8>(Record::VT_LEVEL, level, 2);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_source_file(&mut self, source_file: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_SOURCE_FILE, source_file);
  }
  #[inline]
  pub fn add_source_function(&mut self, source_function: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_SOURCE_FUNCTION, source_function);
  }
  #[inline]
  pub fn add_source_line(&mut self, source_line: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_SOURCE_LINE, source_line, 0);
  }
  #[inline]
  pub fn add_source_column(&mut self, source_column: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_SOURCE_COLUMN, source_column, 0);
  }
  #[inline]
  pub fn add_thread_id(&mut self, thread_id: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_THREAD_ID, thread_id, 0);
  }
  #[inline]
  pub fn add_thread_name(&mut self, thread_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_THREAD_NAME, thread_name);
  }
  #[inline]
  pub fn add_process_id(&mut self, process_id: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_PROCESS_ID, process_id, 0);
  }
  #[inline]
  pub fn add_process_name(&mut self, process_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_PROCESS_NAME, process_name);
  }
  #[inline]
  pub fn add_host_name(&mut self, host_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_HOST_NAME, host_name);
  }
  #[inline]
  pub fn add_container_id(&mut self, container_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_CONTAINER_ID, container_id);
  }
  #[inline]
  pub fn add_app_name(&mut self, app_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_APP_NAME, app_name);
  }
  #[inline]
  pub fn add_app_version(&mut self, app_version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_APP_VERSION, app_version);
  }
  #[inline]
  pub fn add_environment(&mut self, environment: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_ENVIRONMENT, environment);
  }
  #[inline]
  pub fn add_user_id(&mut self, user_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_USER_ID, user_id);
  }
  #[inline]
  pub fn add_session_id(&mut self, session_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_SESSION_ID, session_id);
  }
  #[inline]
  pub fn add_request_id(&mut self, request_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_REQUEST_ID, request_id);
  }
  #[inline]
  pub fn add_trace_id(&mut self, trace_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_TRACE_ID, trace_id);
  }
  #[inline]
  pub fn add_span_id(&mut self, span_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_SPAN_ID, span_id);
  }
  #[inline]
  pub fn add_coroutine_id(&mut self, coroutine_id: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_COROUTINE_ID, coroutine_id, 0);
  }
  #[inline]
  pub fn add_exception_type(&mut self, exception_type: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_EXCEPTION_TYPE, exception_type);
  }
  #[inline]
  pub fn add_exception_message(&mut self, exception_message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_EXCEPTION_MESSAGE, exception_message);
  }
  #[inline]
  pub fn add_exception_stacktrace(&mut self, exception_stacktrace: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_EXCEPTION_STACKTRACE, exception_stacktrace);
  }
  #[inline]
  pub fn add_exception_code(&mut self, exception_code: i32) {
    self.fbb_.push_slot::<i32>(Record::VT_EXCEPTION_CODE, exception_code, 0);
  }
  #[inline]
  pub fn add_labels(&mut self, labels: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_LABELS, labels);
  }
  #[inline]
  pub fn add_lsn(&mut self, lsn: u64) {
    self.fbb_.push_slot::<u64>(Record::VT_LSN, lsn, 0);
  }
  #[inline]
  pub fn add_prev_hash(&mut self, prev_hash: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_PREV_HASH, prev_hash);
  }
  #[inline]
  pub fn add_security_gap(&mut self, security_gap: bool) {
    self.fbb_.push_slot::<bool>(Record::VT_SECURITY_GAP, security_gap, false);
  }
  #[inline]
  pub fn add_audit_tags(&mut self, audit_tags: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_AUDIT_TAGS, audit_tags);
  }
  #[inline]
  pub fn add_ext_data(&mut self, ext_data: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_EXT_DATA, ext_data);
  }
  #[inline]
  pub fn add_ext_crc32c(&mut self, ext_crc32c: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_EXT_CRC32C, ext_crc32c, 0);
  }
  #[inline]
  pub fn add_pool_index(&mut self, pool_index: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_POOL_INDEX, pool_index, 0);
  }
  #[inline]
  pub fn add_flags(&mut self, flags: u32) {
    self.fbb_.push_slot::<u32>(Record::VT_FLAGS, flags, 0);
  }
  #[inline]
  pub fn add_content_hash(&mut self, content_hash: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Record::VT_CONTENT_HASH, content_hash);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Record<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Record::VT_SIGNATURE,"signature");
    self.fbb_.required(o, Record::VT_PREV_HASH,"prev_hash");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Record<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Record");
      ds.field("id_hi", &self.id_hi());
      ds.field("id_lo", &self.id_lo());
      ds.field("timestamp_hi", &self.timestamp_hi());
      ds.field("timestamp_lo", &self.timestamp_lo());
      ds.field("signature", &self.signature());
      ds.field("origin_lsn", &self.origin_lsn());
      ds.field("level", &self.level());
      ds.field("message", &self.message());
      ds.field("source_file", &self.source_file());
      ds.field("source_function", &self.source_function());
      ds.field("source_line", &self.source_line());
      ds.field("source_column", &self.source_column());
      ds.field("thread_id", &self.thread_id());
      ds.field("thread_name", &self.thread_name());
      ds.field("process_id", &self.process_id());
      ds.field("process_name", &self.process_name());
      ds.field("host_name", &self.host_name());
      ds.field("container_id", &self.container_id());
      ds.field("app_name", &self.app_name());
      ds.field("app_version", &self.app_version());
      ds.field("environment", &self.environment());
      ds.field("user_id", &self.user_id());
      ds.field("session_id", &self.session_id());
      ds.field("request_id", &self.request_id());
      ds.field("trace_id", &self.trace_id());
      ds.field("span_id", &self.span_id());
      ds.field("coroutine_id", &self.coroutine_id());
      ds.field("exception_type", &self.exception_type());
      ds.field("exception_message", &self.exception_message());
      ds.field("exception_stacktrace", &self.exception_stacktrace());
      ds.field("exception_code", &self.exception_code());
      ds.field("labels", &self.labels());
      ds.field("lsn", &self.lsn());
      ds.field("prev_hash", &self.prev_hash());
      ds.field("security_gap", &self.security_gap());
      ds.field("audit_tags", &self.audit_tags());
      ds.field("ext_data", &self.ext_data());
      ds.field("ext_crc32c", &self.ext_crc32c());
      ds.field("pool_index", &self.pool_index());
      ds.field("flags", &self.flags());
      ds.field("content_hash", &self.content_hash());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Record`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_record_unchecked`.
pub fn root_as_record(buf: &[u8]) -> Result<Record<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Record>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Record` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_record_unchecked`.
pub fn size_prefixed_root_as_record(buf: &[u8]) -> Result<Record<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Record>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Record` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_record_unchecked`.
pub fn root_as_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Record<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Record<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Record` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_record_unchecked`.
pub fn size_prefixed_root_as_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Record<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Record<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Record and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Record`.
pub unsafe fn root_as_record_unchecked(buf: &[u8]) -> Record<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Record>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Record and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Record`.
pub unsafe fn size_prefixed_root_as_record_unchecked(buf: &[u8]) -> Record<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Record>(buf) }
}
pub const RECORD_IDENTIFIER: &str = "SIF1";

#[inline]
pub fn record_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, RECORD_IDENTIFIER, false)
}

#[inline]
pub fn record_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, RECORD_IDENTIFIER, true)
}

#[inline]
pub fn finish_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Record<'a>>) {
  fbb.finish(root, Some(RECORD_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Record<'a>>) {
  fbb.finish_size_prefixed(root, Some(RECORD_IDENTIFIER));
}
