[package]
name = "dologger-core-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
dologger-core = { path = ".." }

[[bin]]
name = "fuzz_ring_buffer"
path = "fuzz_targets/fuzz_ring_buffer.rs"
test = false
doc = false

[[bin]]
name = "fuzz_toml_config"
path = "fuzz_targets/fuzz_toml_config.rs"
test = false
doc = false

[[bin]]
name = "fuzz_sif_record"
path = "fuzz_targets/fuzz_sif_record.rs"
test = false
doc = false

[[bin]]
name = "fuzz_kv_frame"
path = "fuzz_targets/fuzz_kv_frame.rs"
test = false
doc = false
